background = #000000
foreground = #ffffff
cursor-color = #00ccff
selection-background = #1a1a1a
selection-foreground = #ffffff
palette = 0=#000000
palette = 1=#ff0055
palette = 2=#00ff99
palette = 3=#e5e510
palette = 4=#00ccff
palette = 5=#cc66ff
palette = 6=#00ffff
palette = 7=#cccccc
palette = 8=#666666
palette = 9=#ff3366
palette = 10=#66ffbb
palette = 11=#ffff66
palette = 12=#66ddff
palette = 13=#dd99ff
palette = 14=#66ffff
palette = 15=#ffffff
