set -g status-style "bg=#000000,fg=#ffffff"
set -g message-style "bg=#1a1a1a,fg=#00ccff"
set -g pane-border-style "fg=#333333"
set -g pane-active-border-style "fg=#00ccff"
set -g window-status-current-style "bg=#00ccff,fg=#000000,bold"
set -g window-status-style "bg=#000000,fg=#666666"
