$color = rgba(0,0,0,1.0)
$inner_color = rgba(0,0,0,0.8)
$outer_color = rgba(212,207,196,1.0)
$font_color = rgba(212,207,196,1.0)
$check_color = rgba(125,143,157,1.0)
$font_color_muted = rgba(60,56,54,1.0)
